name: QEMU build (aarch64-softmmu)

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: ./configure --target-list=aarch64-softmmu
    - name: make
      run: make -j
    - name: make check
      run: make -j check
    - uses: actions/upload-artifact@master
      with:
        name: qemu-system-aarch64
        path: aarch64-softmmu/qemu-system-aarch64
